// server.js

/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();
let bodyParser = require('body-parser');

console.log('Express Dependencies')


app.use('/public', express.static(process.cwd() + '/public'));

const userRoutes = require('./routes/users');
app.use('/users', userRoutes);

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });
  
app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })


/*app.use('/json', (req, res, next) => {
  console.log(req.method + " " + req.path + " " + 
 " - " + " " + req.ip);
  next();
}); 
*/

app.get('/now', function(req, res, next) {
  req.time = new Date().toString();  // get date
  next();
}, function(req, res) {
  res.json({time: req.time});
});

app.get('/:word/echo', function(req, res) {
  let {word} = req.params;
  res.json({echo: word});
});

app.get('/express', (req, res, next) => {
  res.send('Hello Express');
}) 

app.get("/json_", (req, res) => {
  res.json({message: "Hello json"});
});

app.use(bodyParser.urlencoded({extended: false}));
app.use(bodyParser.json());

app.get('/nameGet', (req, res, next) => {
  let firstName = req.query.first;
  let lastName = req.query.last;
  res.json({
    name: `${firstName} ${lastName}`
  });
});


app.get('/test', (req, res, next) => {
  res.status(200).send('OK');;
  next();
}); 

// Respond not found to all the wrong routes
app.use(function(req, res, next){
  res.status(404);
  res.type('txt').send('Route Not found');
});

// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})



//Listen on port set in environment variable or default to 3001

const port = process.env.PORT || 3001;

const server = app.listen(port, () => console.log(`Example app listening on port ${port}!`));

server.keepAliveTimeout = 120 * 1000;
server.headersTimeout = 120 * 1000;

